# VM: osm-import-vm — always-on import/updater host.
# Mirrors infra-solution/modules/vm.bicep.
#
#   - E32-8s_v5 (128 GB RAM, 8 active vCPU on a 32-vCPU SKU)
#   - 128 GB Premium_LRS OS disk (from image)
#   - Premium SSD v2 data disk on /mnt/data (zonal)
#   - Standard Static Public IP on the NIC (default on) for SSH-in +
#     deterministic IPv4 egress — no NAT Gateway, no Bastion.
#   - User-assigned managed identity for azcopy MSI auth
#
# NOTE: Premium SSD v2 requires the disk and VM to be deployed into a
# specific availability zone. The Standard PIP is also made zonal to
# match.

variable "vm_name" {
  type = string
}

variable "resource_group_name" {
  type = string
}

variable "location" {
  type = string
}

variable "vm_size" {
  type    = string
  default = "Standard_E32-8s_v5"
}

variable "admin_username" {
  type = string
}

variable "admin_password" {
  description = "Required when use_ssh_key=false."
  type        = string
  default     = ""
  sensitive   = true
}

variable "use_ssh_key" {
  type    = bool
  default = false
}

variable "ssh_public_key" {
  description = "OpenSSH format. Required when use_ssh_key=true."
  type        = string
  default     = ""
}

variable "subnet_id" {
  type = string
}

variable "data_disk_size_gb" {
  type    = number
  default = 256
}

variable "data_disk_iops" {
  type    = number
  default = 3000
}

variable "data_disk_throughput_mbps" {
  type    = number
  default = 750
}

variable "availability_zone" {
  type    = string
  default = "1"
  validation {
    condition     = contains(["1", "2", "3"], var.availability_zone)
    error_message = "availability_zone must be 1, 2, or 3."
  }
}

variable "os_disk_size_gb" {
  type    = number
  default = 128
}

variable "os_disk_storage_account_type" {
  type    = string
  default = "Premium_LRS"
}

variable "enable_public_ip" {
  type    = bool
  default = true
}

# ── Runtime env baked into /etc/profile.d/osm-env.sh at deploy time. ──
variable "key_vault_name" {
  type    = string
  default = ""
}

variable "pg_password_secret_name" {
  type    = string
  default = "pg-admin-password"
}

variable "pg_server_fqdn" {
  type    = string
  default = ""
}

variable "pg_admin_login" {
  type    = string
  default = "osmuser"
}

variable "pg_database_name" {
  type    = string
  default = "osm"
}

variable "storage_account_name" {
  type    = string
  default = ""
}

variable "container_name" {
  type    = string
  default = "osmscanning"
}

variable "init_osm_script_path" {
  description = "Filesystem path to init-osm.sh (shared with the Bicep stack)."
  type        = string
}

variable "update_osm_script_path" {
  description = "Filesystem path to update-osm.sh (shared with the Bicep stack)."
  type        = string
}

variable "cloud_init_path" {
  description = "Filesystem path to cloud-init.yaml (shared with the Bicep stack)."
  type        = string
}

locals {
  nic_name       = "${var.vm_name}-nic"
  pip_name       = "${var.vm_name}-pip"
  mi_name        = "${var.vm_name}-mi"
  data_disk_name = "${var.vm_name}-data"

  cloud_init        = file(var.cloud_init_path)
  init_osm_script   = file(var.init_osm_script_path)
  update_osm_script = file(var.update_osm_script_path)

  # /etc/profile.d/osm-env.sh — mirrors the bicep osmEnvFile join().
  osm_env_file = <<-EOT
    # Auto-generated by infra-solution-tf/modules/vm at deploy time.
    # Sourced by /etc/profile so interactive shells (and init-osm.sh /
    # update-osm.sh) see the right identity, Key Vault, PostgreSQL and
    # storage settings without operators having to export anything.
    export UAI_CLIENT_ID='${azurerm_user_assigned_identity.mi.client_id}'
    export AZCOPY_AUTO_LOGIN_TYPE='MSI'
    export AZCOPY_MSI_CLIENT_ID='${azurerm_user_assigned_identity.mi.client_id}'
    export KEY_VAULT_NAME='${var.key_vault_name}'
    export PG_PASSWORD_SECRET_NAME='${var.pg_password_secret_name}'
    export PGHOST='${var.pg_server_fqdn}'
    export PGUSER='${var.pg_admin_login}'
    export PGDATABASE='${var.pg_database_name}'
    export PGSSLMODE='require'
    export STORAGE_ACCOUNT='${var.storage_account_name}'
    export CONTAINER_NAME='${var.container_name}'
  EOT

  # Installer script that base64-decodes init/update scripts + osm-env.sh
  # onto disk on first boot. Mirrors the bicep format() call.
  installer_script = <<-EOT
    #!/usr/bin/env bash
    set -euo pipefail
    USER_NAME='${var.admin_username}'
    HOME_DIR="/home/$USER_NAME"
    install -d -o "$USER_NAME" -g "$USER_NAME" -m 0755 "$HOME_DIR"
    echo '${base64encode(local.init_osm_script)}' | base64 -d | tr -d '\r' > "$HOME_DIR/init-osm.sh"
    echo '${base64encode(local.update_osm_script)}' | base64 -d | tr -d '\r' > "$HOME_DIR/update-osm.sh"
    chmod 0755 "$HOME_DIR/init-osm.sh" "$HOME_DIR/update-osm.sh"
    chown "$USER_NAME:$USER_NAME" "$HOME_DIR/init-osm.sh" "$HOME_DIR/update-osm.sh"
    echo '${base64encode(local.osm_env_file)}' | base64 -d | tr -d '\r' > /etc/profile.d/osm-env.sh
    chmod 0644 /etc/profile.d/osm-env.sh
  EOT

  # Change-detection marker — plays the role of Bicep's `forceUpdateTag`.
  # The Linux CustomScript public-settings schema only whitelists a
  # fixed set of keys; `timestamp` (int) is the documented way to
  # trigger a re-run. Derive it from the first 8 hex chars of the
  # sha256 so it is stable content-hash, not a wall-clock value.
  script_timestamp = parseint(substr(sha256("${local.init_osm_script}${local.update_osm_script}${local.osm_env_file}"), 0, 8), 16)
}

resource "azurerm_user_assigned_identity" "mi" {
  name                = local.mi_name
  location            = var.location
  resource_group_name = var.resource_group_name
}

resource "azurerm_public_ip" "pip" {
  count               = var.enable_public_ip ? 1 : 0
  name                = local.pip_name
  location            = var.location
  resource_group_name = var.resource_group_name
  allocation_method   = "Static"
  sku                 = "Standard"
  ip_version          = "IPv4"
  zones               = [var.availability_zone]

  # PIP is create-once for the lifetime of the VM. Any drift Azure
  # returns (zones, sku, sku_tier, ip_version, allocation_method,
  # domain_name_label, idle_timeout, tags, etc.) would otherwise
  # trigger a destroy+recreate that fails hard because ARM won't let
  # you delete a PIP while it is still attached to a NIC ipconfig.
  # `ignore_changes = all` freezes the resource after create.
  # If you ever need to legitimately change the PIP, taint it explicitly:
  #   terraform taint 'module.vm.azurerm_public_ip.pip[0]'
  lifecycle {
    ignore_changes = all
  }
}

resource "azurerm_network_interface" "nic" {
  name                = local.nic_name
  location            = var.location
  resource_group_name = var.resource_group_name

  ip_configuration {
    name                          = "ipconfig1"
    subnet_id                     = var.subnet_id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = var.enable_public_ip ? azurerm_public_ip.pip[0].id : null
  }
}

resource "azurerm_managed_disk" "data" {
  name                 = local.data_disk_name
  location             = var.location
  resource_group_name  = var.resource_group_name
  storage_account_type = "PremiumV2_LRS"
  create_option        = "Empty"
  disk_size_gb         = var.data_disk_size_gb
  disk_iops_read_write = var.data_disk_iops
  disk_mbps_read_write = var.data_disk_throughput_mbps
  zone                 = var.availability_zone
}

resource "azurerm_linux_virtual_machine" "vm" {
  name                            = var.vm_name
  location                        = var.location
  resource_group_name             = var.resource_group_name
  size                            = var.vm_size
  admin_username                  = var.admin_username
  admin_password                  = var.use_ssh_key ? null : var.admin_password
  disable_password_authentication = var.use_ssh_key
  network_interface_ids           = [azurerm_network_interface.nic.id]
  zone                            = var.availability_zone
  custom_data                     = base64encode(local.cloud_init)

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.mi.id]
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = var.os_disk_storage_account_type
    disk_size_gb         = var.os_disk_size_gb
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "ubuntu-24_04-lts"
    sku       = "server"
    version   = "latest"
  }

  dynamic "admin_ssh_key" {
    for_each = var.use_ssh_key ? [1] : []
    content {
      username   = var.admin_username
      public_key = var.ssh_public_key
    }
  }

  # OS disk size / SKU are effectively immutable on an existing VM.
  # Match the Bicep `osDiskOmitImmutableProps=true` default by ignoring
  # drift on those two properties post-create.
  lifecycle {
    ignore_changes = [
      os_disk[0].disk_size_gb,
      os_disk[0].storage_account_type,
    ]
  }
}

resource "azurerm_virtual_machine_data_disk_attachment" "data" {
  managed_disk_id    = azurerm_managed_disk.data.id
  virtual_machine_id = azurerm_linux_virtual_machine.vm.id
  lun                = 0
  # Premium SSD v2 does not support host caching; must be None.
  caching = "None"
}

# ─────────────────────────────────────────────────────────────────────────────
# CustomScript extension — deploy init-osm.sh + update-osm.sh + osm-env.sh.
#
# The `settings` hash plays the same role as Bicep's `forceUpdateTag`:
# Terraform re-applies the extension whenever the embedded scripts
# change, so /home/osmadmin/{init,update}-osm.sh stay in sync with the
# files in the repo root.
# ─────────────────────────────────────────────────────────────────────────────
resource "azurerm_virtual_machine_extension" "install_osm_scripts" {
  name                       = "installOsmScripts"
  virtual_machine_id         = azurerm_linux_virtual_machine.vm.id
  publisher                  = "Microsoft.Azure.Extensions"
  type                       = "CustomScript"
  type_handler_version       = "2.1"
  auto_upgrade_minor_version = true

  settings = jsonencode({
    timestamp = local.script_timestamp
  })

  protected_settings = jsonencode({
    script = base64encode(local.installer_script)
  })

  depends_on = [
    azurerm_virtual_machine_data_disk_attachment.data,
  ]
}

output "vm_id" {
  value = azurerm_linux_virtual_machine.vm.id
}

output "vm_name" {
  value = azurerm_linux_virtual_machine.vm.name
}

output "managed_identity_id" {
  value = azurerm_user_assigned_identity.mi.id
}

output "managed_identity_principal_id" {
  value = azurerm_user_assigned_identity.mi.principal_id
}

output "managed_identity_client_id" {
  value = azurerm_user_assigned_identity.mi.client_id
}

output "public_ip" {
  value = var.enable_public_ip ? azurerm_public_ip.pip[0].ip_address : ""
}

output "private_ip" {
  value = azurerm_network_interface.nic.private_ip_address
}
